Fix map status is not updated
osuAkatsuki/bancho.py pull request #280
Opened 2022-08-14 08:23 UTC by TrueRou

What the problem is:
The ranked status of the map won't update if its md5 is not changed.

When the problem will happen:
A bancho new map changed its status from Qualified to Ranked.
An bancho old map changed its status from Loved to Ranked.

What I did:
Update ranked status if the map is not frozen.

2022-08-29 22:24 UTC, cmyui commented on app/objects/beatmap.py
> +                            )
hey - i don't believe this change will be saved into sql

2022-08-29 22:24 UTC, cmyui requested changes
see comment

2022-09-01 07:43 UTC, arily commented on app/objects/beatmap.py
> +                            )
there's a `updated_maps.append(old_map)` right after these lines, and 
https://github.com/TrueRou/bancho.py/blob/f5590ff474177cc0d89382211ffc03f288fc5b4e/app/objects/beatmap.py#L719
self._save_to_sql() at the end.
Could you please check again if changes are not reflected to database?

2022-09-01 08:10 UTC, arily commented on app/objects/beatmap.py
> +                            )
Trou is busy preparing for gaokao test and might not be available for quite a while.

2023-01-27 15:14 UTC, closed without merging