Migrate pp system implementation to rosu-pp-py
osuAkatsuki/bancho.py pull request #315
Opened 2022-12-24 17:31 UTC by 7mochi

Closes #283 

Issues:
- RX pp is nerfed
  - https://github.com/MaxOhn/rosu-pp/blob/main/src/osu/pp.rs#L479-L480
  - https://github.com/MaxOhn/rosu-pp/blob/main/src/osu/pp.rs#L520-L522
  - https://github.com/MaxOhn/rosu-pp/blob/main/src/osu/pp.rs#L591-L593
- AP is not supported and returns NM pp value instead
  - https://github.com/MaxOhn/rosu-pp/blob/main/src/mods.rs#L77-L86

The problems mentioned above have been sort of fixed in [my fork](https://github.com/osuperu/rosu-pp), but I don't think you would like to use it, so idk what would be the right way to deal with the issues

2022-12-24 17:43 UTC, minisbett commented
Why would you make the AR factor 0 on relax

2022-12-24 17:44 UTC, minisbett commented
This is the worst relax implementation I've ever seen

2022-12-24 17:48 UTC, minisbett commented
Nvm it's the bancho implementation I forgot it sucks

2022-12-24 17:48 UTC, minisbett commented
We will definitely have to fork rosupp i don't think anyone here wants 1k pp plays getting nerfed to 200-300pp

2022-12-24 17:49 UTC, tsunyoku commented
tbh just use https://github.com/osuAkatsuki/akatsuki-pp-rs since it's rosu-pp too.
just note the relax system lies in osu_2019 and not osu, because adapting 2022 for relax was awful

i'd also like to note that rosu_pp_py is not up to date with the latest rosu-pp version (due to rewrite stuff), so i don't think making this change is a good idea right now

2022-12-24 17:49 UTC, minisbett commented
Also better for customization so for this PR I would suggest putting in rosupp-py as a submodule instead

2022-12-24 17:50 UTC, minisbett commented
> tbh just use https://github.com/osuAkatsuki/akatsuki-pp-rs since it's rosu-pp too. just note the relax system lies in osu_2019 and not osu, because adapting 2022 for relax was awful
> 
> i'd also like to note that rosu_pp_py is not up to date with the latest rosu-pp version (due to rewrite stuff), so i don't think making this change is a good idea right now

Or that would work

2022-12-24 17:51 UTC, 7ez commented
just replace vn pp with rosu-pp, I don't see a sense in replacing the whole std calc with it

2022-12-24 17:54 UTC, tsunyoku commented
> just replace vn pp with rosu-pp, I don't see a sense in replacing the whole std calc with it

because we get to use a single system across the board which makes life much easier
also oppai is problematic & peace is outdated and doesn't support converts

however, we need to wait for rosu-pp-py to be updated at the very least; unless we decide to just use akatsuki's version before then

2022-12-24 17:59 UTC, 7mochi commented
> tbh just use https://github.com/osuAkatsuki/akatsuki-pp-rs since it's rosu-pp too. just note the relax system lies in osu_2019 and not osu, because adapting 2022 for relax was awful
> 
> i'd also like to note that rosu_pp_py is not up to date with the latest rosu-pp version (due to rewrite stuff), so i don't think making this change is a good idea right now

I could try adapting that version with the latest rosu-pp changes. Would that work?

2022-12-24 18:05 UTC, tsunyoku commented
> > tbh just use https://github.com/osuAkatsuki/akatsuki-pp-rs since it's rosu-pp too. just note the relax system lies in osu_2019 and not osu, because adapting 2022 for relax was awful
> > i'd also like to note that rosu_pp_py is not up to date with the latest rosu-pp version (due to rewrite stuff), so i don't think making this change is a good idea right now
> 
> I could try adapting that version with the latest rosu-pp changes. Would that work?

it already includes them, it’s up to date with rosu-pp’s main branch

2022-12-24 18:08 UTC, minisbett commented
Either way, I still suggest putting rosupp-py in as a submodule so it can be modified

2022-12-24 18:20 UTC, cmyui commented
nice work so far, thanks for taking this responsibility on!

2022-12-24 18:27 UTC, cmyui commented
also, looks like i must've broke pre-commit ci at some point 🤔

2022-12-24 23:57 UTC, 7mochi commented
> > > tbh just use https://github.com/osuAkatsuki/akatsuki-pp-rs since it's rosu-pp too. just note the relax system lies in osu_2019 and not osu, because adapting 2022 for relax was awful
> > > i'd also like to note that rosu_pp_py is not up to date with the latest rosu-pp version (due to rewrite stuff), so i don't think making this change is a good idea right now
> > 
> > 
> > I could try adapting that version with the latest rosu-pp changes. Would that work?
> 
> it already includes them, it’s up to date with rosu-pp’s main branch

Which python bindings would I use with akatsuki-pp-rs?

2022-12-25 06:17 UTC, cmyui commented
> Which python bindings would I use with akatsuki-pp-rs?

@tsunyoku if you could help him out a bit here would be very epic 11/10

2022-12-27 00:38 UTC, 7mochi commented
> > Which python bindings would I use with akatsuki-pp-rs?
> 
> @tsunyoku if you could help him out a bit here would be very epic 11/10

akatsuki-pp-rs doesn't have python bindings yet so idk know how I should proceed 💀
I guess I'll wait until there is one because I haven't been able to adapt those changes to rosu-pp-py on my own

2022-12-27 00:42 UTC, minisbett commented
> > > Which python bindings would I use with akatsuki-pp-rs?
> > 
> > 
> > @tsunyoku if you could help him out a bit here would be very epic 11/10
> 
> akatsuki-pp-rs doesn't have python bindings yet so idk know how I should proceed 💀 I guess I'll wait until there is one because I haven't been able to adapt those changes to rosu-pp-py on my own

Since akatsuki-pp-rs is based on rosu-pp shouldn't the normal rosu-pp bindings work? Idk how python bindings work but if I imagine it correct it's basically just saying access these and these methods and the methods should have the same signatures

2022-12-27 19:33 UTC, 7mochi commented
I think I got it to work, but there's no bindings repo in osuAkatsuki so i can't make a PR yet, anyways, i've tested it in my fork and it works. Could you guys check it? @cmyui @tsunyoku 

Changes:
- rosu-pp-py: https://github.com/osuperu/rosu-pp-py/commit/70329714e7f5e3bcb402ba985540a154da15f0ad
- akatsuki-pp-rs: https://github.com/osuperu/rosu-pp/commit/cd002b0c3e7228058684b8e3345258ff8efb5a9f
- bancho.py (performance.py | calculate_performances_std)
```py
if score["mods"] and Mods.RELAX & score["mods"]:
    calculator.set_acc_2019(acc)
    result = calculator.performance_2019(map)
else:
    result = calculator.performance(map)
```

2022-12-27 22:35 UTC, cmyui commented
nice, @tsunyoku is working on making bindings for akatsuki's pp system

2022-12-27 22:35 UTC, cmyui commented
i'll review this shortly

2022-12-27 22:45 UTC, cmyui commented
@7mochi hey, do you have any uncommitted changes? i'd like to take over the pr for a bit when you're ready

2022-12-27 23:01 UTC, 7mochi commented
> @7mochi hey, do you have any uncommitted changes? i'd like to take over the pr for a bit when you're ready

Just that piece of code I posted earlier

2022-12-27 23:48 UTC, tsunyoku commented
hey, made bindings for akatsuki-pp-rs @ https://github.com/osuAkatsuki/akatsuki-pp-py.
all tested including automatic osu_2019 usage when osu!std relax is passed (use the same api as rosu-pp-py examples)

hope this helps :D

2022-12-28 02:49 UTC, cmyui commented on README_CN.md
> +curl https://sh.rustup.rs -sSf | bash -s -- -y
```suggestion
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

2022-12-28 02:49 UTC, cmyui commented on README_DE.MD
> +curl https://sh.rustup.rs -sSf | bash -s -- -y
```suggestion
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

2022-12-28 02:49 UTC, cmyui commented on README.md
> +curl https://sh.rustup.rs -sSf | bash -s -- -y
```suggestion
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

2022-12-28 03:01 UTC, tsunyoku requested changes

2022-12-28 03:01 UTC, tsunyoku commented on app/commands.py
> +                                    modeInt = GameMode.VANILLA_CATCH
```suggestion
                                    mode_int = GameMode.VANILLA_CATCH
```

2022-12-28 03:01 UTC, tsunyoku commented on app/commands.py
> +                                modeInt = GameMode.VANILLA_OSU
```suggestion
                                mode_int = GameMode.VANILLA_OSU
```

2022-12-28 03:01 UTC, tsunyoku commented on app/commands.py
> +                                calculator = Calculator(mods=row["mods"], mode=modeInt)
```suggestion
                                calculator = Calculator(mods=row["mods"], mode=mode_int)
```

2022-12-28 03:01 UTC, tsunyoku commented on app/commands.py
> +                                calculator = Calculator(mods=row["mods"], mode=modeInt)
```suggestion
                                calculator = Calculator(mods=row["mods"], mode=mode_int)
```

2022-12-28 04:00 UTC, cmyui commented
going to refactor the calculate_performances_x functions into a singular interface, now that we can

2022-12-28 04:34 UTC, cmyui commented on app/constants/gamemodes.py
> +        return ret
thought about this one, will keep as is.

property seems more appropriate for things on the instances, e.g. GameMode(0).as_vanilla, whereas this is meant to be used on the class itself, GameMode.valid_gamemodes()

memory leak only applies to methods, not classmethods

2022-12-28 04:45 UTC, cmyui commented
getting close!

2022-12-28 04:47 UTC, cmyui commented
I think we're good to go on this.

Can I get a re-review @tsunyoku, @7mochi please!

2022-12-28 04:47 UTC, cmyui commented
also @alowave223 you should take a look, i think

2022-12-28 04:51 UTC, cmyui commented
ah, found some bugs with callers of `calculate_performances` still using params that were moved into the `scores` param

2022-12-28 05:34 UTC, cmyui commented
ok, things look good now. feel free to review away!

2022-12-28 16:15 UTC, cmyui approved these changes

2022-12-28 16:16 UTC, tsunyoku approved these changes

2022-12-28 16:16 UTC, merged