refactor: api-v2 authorization
osuAkatsuki/bancho.py pull request #366
Opened 2023-01-10 17:47 UTC by alowave223

Here, again, referring to the akatsuki-v2 I've implemented basics of authorization logic. There is many things TODO but I think it's better to make small PR's so we can have track of what we doing.

2023-01-10 21:32 UTC, cmyui commented on app/api/v2/models/sessions.py
> +    expires_at: Union[datetime, None]
prefer optional syntax for 3.9

2023-01-10 21:35 UTC, cmyui commented on app/api/v2/sessions.py
> +    return responses.success(response)
i think we want to implement oauth with client id and secret rather than using name & password like this

see osu api v2 for example

2023-01-10 21:35 UTC, cmyui commented on app/api/v2/sessions.py
> +
should be able to just use partial_update alone
```suggestion
```

2023-01-10 21:36 UTC, cmyui commented on app/api/v2/sessions.py
> +        return responses.failure(message="Failed to create session.")
```suggestion
        return responses.failure(message="Failed to deletesession.")
```

2023-01-10 21:36 UTC, cmyui commented on app/api/v2/sessions.py
> +@router.delete("/sessions")
tbh i might remove the /self things later & replace with /{session_id} but it's fine for now
```suggestion
@router.delete("/sessions/self")
```

2023-01-10 21:37 UTC, cmyui commented on app/repositories/sessions.py
> +async def partial_update(session_id: UUID, **kwargs: Any) -> Mapping[str, Any] | None:
3.10 syntax

2023-01-10 21:39 UTC, cmyui requested changes
Will need changes, the usecases abstraction was something i was looking to avoid until later (like we did in players apis)

also will need to switch to proper oauth

@NiceAesth u have any free cycles to work on this with me any time soon?

2023-01-10 21:41 UTC, cmyui commented
@alowave223 i think it's best if you continue with non-authed endpoints like GETs for other resources - there are plenty to do outside of this for now, notably;

players [DONE]
maps
scores
stats
clans
channels
tourney_pools
tourney_pool_maps

2023-01-10 23:20 UTC, NiceAesth commented
@cmyui I am a bit busier than usual these days, but I can try something either thursday or in the weekends. (I have exams upcoming so this month so yeah)

2023-01-15 10:45 UTC, alowave223 commented
Will be re-done

2023-01-15 10:45 UTC, closed without merging