feat: v2 maps api (get calls only)
osuAkatsuki/bancho.py pull request #373
Opened 2023-01-11 14:59 UTC by cmyui

2023-01-11 22:15 UTC, alowave223 requested changes
We should add most played maps on a server and by a single player as it is used by guweb atm in order to move guweb from v1 to v2

2023-01-11 23:19 UTC, cmyui commented
> We should add most played maps on a server and by a single player as it is used by guweb atm in order to move guweb from v1 to v2

this will be a separate api

2023-01-12 08:22 UTC, cmyui commented on app/api/v2/models/maps.py
> +    server: Literal["osu!", "private"]
this should be moved down to match db table

2023-01-12 08:22 UTC, cmyui commented on app/api/v2/maps.py
> +    server: str,
this should be moved down to match db table; also should test if typing.Literal can/should be used here

2023-01-12 23:52 UTC, cmyui commented on app/api/v2/maps.py
> +    server: str,
avoiding for now - there are other similar things happening elsewhere, might standardize these to use enums later.

2023-01-13 00:23 UTC, merged