file path fixes for osu redirects
osuAkatsuki/bancho.py pull request #550
Opened 2023-11-29 00:24 UTC by cmyui

# Describe your changes

## Related Issues / Projects

## Checklist
- [ ] I've manually tested my code

2023-11-29 00:25 UTC, cmyui commented on app/commands.py
> +    "{idx}. ({pp:.2f}pp) [https://osu.{domain}/b/{map_id} "
```suggestion
    "{idx}. ({pp:.2f}pp) [https://osu.{domain}/beatmapsets/{map_set_id}/{map_id} "
```

2023-11-29 00:25 UTC, cmyui commented on app/objects/beatmap.py
> +      Beatmap.url -> str # https://osu.cmyui.xyz/b/321
```suggestion
      Beatmap.url -> str # https://osu.cmyui.xyz/beatmapsets/123/321
```

2023-11-29 00:25 UTC, cmyui commented on app/api/domains/cho.py
> +                )
```suggestion
                map_url = f"https://osu.{app.settings.DOMAIN}/beatmapsets/#/{self.match_data.map_id}"
```

2023-11-29 00:26 UTC, tsunyoku requested changes
you had one job 😭

/b won't be clickable to a map ingame, it will open in browser even if you have it

there was another pr related to the urls where i said to construct the whole valid url, i'm going to say the same here.

2023-11-29 00:35 UTC, cmyui commented
> you had one job 😭
> 
> /b won't be clickable to a map ingame, it will open in browser even if you have it
> 
> there was another pr related to the urls where i said to construct the whole valid url, i'm going to say the same here.

Was this feedback meant for the other PR? (this PR doesn't do anything related to /b/)

2023-11-29 09:15 UTC, tsunyoku commented
> > you had one job 😭
> 
> > 
> 
> > /b won't be clickable to a map ingame, it will open in browser even if you have it
> 
> > 
> 
> > there was another pr related to the urls where i said to construct the whole valid url, i'm going to say the same here.
> 
> 
> 
> Was this feedback meant for the other PR? (this PR doesn't do anything related to /b/)

diff was showing some beatmap url changes but they're gone now

2023-11-29 09:15 UTC, tsunyoku approved these changes

2023-12-01 18:49 UTC, NiceAesth commented
yell if it breaks lgtm

2023-12-01 18:49 UTC, merged